name: Test

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - master
      - release/*


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: 
          - "3.10"
          - "3.11"
          - "3.12"
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --extra test

      - name: Run tests
        run: uv run pytest tests